# Similar to ConfigMaps but specifically intended to hold confidential data, e.g. SSH keys
# They can be referenced by different Deployments
# Should not be checked into Git repo

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # values in secrets are in base64 format
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==